### ISSUE TITLE
Motion or Face detection 

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#102]
What is HuddlyIQ detecting, Motion or Face 
1. The following code snippet gives accurate count of 0 when no one is in front of the camera. When I move just my hand in front of the camera it starts giving length of 1. Is that expected?  
```
detector.on('DETECTIONS', detections => {
            console.log('People count ', detections.length);
```
2. It seems the above code continuously logs, perhaps every second, even when count has not changed. Is there a way to log only when count changes? 

3. Is it possible to DETECTION say every 5 seconds instead of every second?

**Comment by jontore** [comment]
1. It counts people, so that means any part of a human (so your hand counts as 1). We're working on adding more classes to the model. 

2/3. It triggers as soon as there is a new detection, regardless if the detections has changed. Even though the count is the same, a person might have moved. 

If you want to have less events I suggest you can throttle the detection cb (https://lodash.com/docs/4.17.11#throttle) something like ```
detector.on('DETECTIONS', _.throttle(detections => {
            console.log('People count ', detections.length);
}, 5000));```

**Comment by qmas** [comment]
It throttles. You may close this issue. Thanks
