### ISSUE TITLE
Getting error/warning when 

### ISSUE THREAD

**Issue by qzzf1w** [Huddly/sdk#154]
:::::::::::: Transport Protocol is HLINK ::::::::::::
2019-7-15 | 18:53:26:140 | WARN | SDK DeviceFactory | Preferred device api does not support uvc control interface
2019-7-15 | 18:53:26:143 | ERROR | SDK DeviceFactory | None of the device api's support uvc control interface

Is this expected?

**Comment by brikendr** [comment]
Thank  you for submitting the issue @qzzf1w 

This is expected yes. Probably it is better if the second log message is annotated as a warning instead of error,  that is because the `device-api-usb` module which is used for communication and usb device control (open, close, claim vsc interface/endpoints etc) does not support standard UVC controls such as zoom, pan, tilt, brightness adjustments etc. It might be that in the future we will release a similar module such as `device-api-usb` that supports uvc controls. As for now the above messages are to be expected.

I will create a PR that communicates this issue more appropriately.
Thanks for your contribution.
