### ISSUE TITLE
Call to getDetector turns autozoom_enabled to true ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#176]
Both the following code lines turn the camera autozoom_enabled to true. Is it normal? 
`const detector = cameraManager.getDetector({ shouldAutoFrame: true});`
or
`const detector = cameraManager.getDetector({ shouldAutoFrame: false});`

Is it possible to count people without turning autozoom  to true or keeping autozoom_enabled to false ?

Camera:
serialNumber    =  B40J00164
softwareVersion =  HuddlyIQ-1.2.16-38450
Sdk:
"@huddly/device-api-usb": "^0.1.5",
"@huddly/sdk": "^0.1.14",
Node v8.9.4
npm 6.10.1

**Comment by brikendr** [comment]
Hi @qmas,
Thank you for using our SDK, please upgrade your device-api-usb and sdk to latest released versions to get patches and bugfixes inplace.

`shouldAutoFrame` is a configuration option of the autozoom feature. By default it is set to `true` and it means that when autozoom is running on the camera, autoframing of the people in the view will be run. The main reason this option can be configured is so that you can show how the camera would frame the people in the view without actually doing the autoframing. This can be done by subscribing to `FRAMING` events on the detector (similar to when you subscribe to `DETECTIONS` event / people count).

It is not possible to get people count if the autozoom feature is not enabled on the camera.

Hopefully this answers your question.

**Comment by brikendr** [comment]
@qmas closing the issue due to inactivity. Please reopen if necessary.
