### ISSUE TITLE
Multiple instances of Huddly sdk

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#177]
Can I run multiple instances of Huddly sdk? While people count is running and logging continuously, how can I run another instance to check camera info or camera status.

**Comment by brikendr** [comment]
Hi @qmas,
It is not possible to run multiple Huddly SDK instance targeting the same camera. The reason is that the SDK instance will occupy a what's called VSC (Vendor Specific Command) interface which is used for exchanging messages between host and camera. On our Huddly IQ, there is only one such interface available from the USB stack, hence the restriction.

However, nothing stops you from doing concurrent things using one Huddly SDK instance. It is possible to setup a people count handler in one thread on your code and query camera info or camera status on another thread, as long as you are using the same Huddly SDK instance on your code.

Hope this answerss your question.

**Comment by brikendr** [comment]
@qmas closing this issue since there has not been any activity on it. Please feel free to reopen it or submit another issue for other unclarities.
