### ISSUE TITLE
(Question) How to capture video in Windows

### ISSUE THREAD

**Issue by FreedCapybara** [Huddly/sdk#190]
As mentioned here https://github.com/Huddly/sdk/issues/189 the camera supports UVC, but I've been having a pretty hard time getting it to work.

The code will run on a Windows machine, and would preferably be coded in Python (as dictated by the customer/project).

Could you provide an example, or a link to something that works? (non-Python examples welcome 👍)

**What I've tried so far**

OpenCV didn't seem to work for me https://techoverflow.net/2018/12/18/how-to-take-a-webcam-picture-using-opencv-in-python/, as the capture output failed to render.

I've tried FFmpeg https://trac.ffmpeg.org/wiki/Capture/Webcam with the command `ffmpeg -y -f vfwcap -r 25 -i 0 out.mp4`, but the video output file fails to play.

I tried these instructions from pyuvc, but I think they just caused me to screw up my Huddly driver (which I reset): https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md

I also messed with trying to set up libgphoto2, but I think I got lost in all the mingw32/64 cross-platform compilation nonsense.

Based on the FFmpeg output of `ffmpeg -y -f vfwcap -i list`, I'm wondering if the device is being detected properly. It seems to give the same output whether I have the camera connected or not. It could also be that FFmpeg is the wrong tool.

I hope there's something obvious that I'm missing!

**Comment by brikendr** [comment]
Hey @FreedCapybara 

Thank you for submitting your question. I can give you a couple of examples using different tools for streaming UVC on Huddly IQ.

I guess the first thing you need to check is that the camera has enumerated properly on your machine and you are ablet to open the stream with the standard windows camera application.

#### ffmpeg
Use `dshow` instead of `vfwcap` when listing the cameras on your computer:
`ffmpeg -list_devices true -f dshow -i dummy` according to [ffmpeg docs](https://trac.ffmpeg.org/wiki/DirectShow)

Make sure you see the `Huddly IQ` as part of the device list. Then you can use the following command to record a video with the Huddly IQ:

```
ffmpeg -f dshow -i 'video=Huddly IQ:audio=Microphone (Huddly IQ)' -vframes 300 -ac 1 -ar 48000 sample_video_iq.mp4
```
- `-vframes 300` is the number of video frames to output.
- `-ac 1` set the numer of audio channels to one
- `-ar 48000` audio sampling frequency

#### open-cv
Unfortunately I dont have a development windows machine setup to test with open-cv but here is a code-snippet that might work for you:

```
from imutils.video import VideoStream
import cv2
import time

vs = VideoStream(src=0, resolution=(1920, 1080)).start()
time.sleep(2.0)

while True:
  # read the frame from the camera and send it to the server
  frame = vs.read()
  cv2.imshow('cam', frame)
  cv2.waitKey(10)
```
Taken (with little modification) from this [site](https://www.pyimagesearch.com/2019/04/15/live-video-streaming-over-network-with-opencv-and-imagezmq/)

#### javascript/nodejs
Another alternative is to use webrtc to stream Huddly IQ on your browser if that is applicable in your case:

```
const video = document.querySelector('video');
const constrainst = {
video: {
    width: 1920,
    height: 1080
  }
}
const stream = await navigator.mediaDevices.getUserMedia(constraints);
const videoTracks = stream.getVideoTracks();
video.srcObject = stream;
```
Codesnippet taken from [WebRTC Samples](https://webrtc.github.io/samples/src/content/getusermedia/gum/)

Hopefully this is useful.

**Comment by FreedCapybara** [comment]
Very helpful, thank you!

The Huddly camera does indeed appear in the device list with your `dshow` version 👍 Unfortunately for some reason I still get a bad file when I run `ffmpeg -f dshow -i "video=Huddly IQ:audio=Microphone (Huddly IQ)" -vframes 300 -ac 1 -ar 48000 sample_video_iq.mp4`, though the command does run and I get a file with nonzero size. I'm able to play [public test videos](https://gist.github.com/jsturgis/3b19447b304616f18657) on my device after downloading, so I don't think my player would be the issue.

I simplified that Python script even further:
```python
from imutils.video import VideoStream
import cv2
import time

vs = VideoStream(src=0, resolution=(1920, 1080)).start()

frame = vs.read()
cv2.imshow('cam', frame)
time.sleep(10)
```
But for some reason I get nothing:
![opencv](https://user-images.githubusercontent.com/7003723/65483318-ba4c3680-de69-11e9-9ea3-994384dbdc00.gif)

I wish I was doing something with the web because it seems to work great on pages like this: https://webrtc.github.io/samples/src/content/getusermedia/gum/ or https://googlechrome.github.io/samples/image-capture/grab-frame-take-photo.html

I bet it's something simple that I'm missing. I tried installing the Huddly software hoping that it would add the correct driver and everything would magically work, but still no dice 😕

**Comment by brikendr** [comment]
Hi @FreedCapybara 

I tested the following python codesnippet locally and it worked with a Huddly IQ. Please keep in mind that the host machine i ran the code on had only one camera connected, thus `src=0` option.

Code Snipped:
```
from imutils.video import VideoStream
import cv2
import time

# Using src=0 since Huddly IQ is the only camera connected to the host machine
vs = VideoStream(src=0, resolution=(1920, 1080)).start()

while True:
    frame = vs.read()
    cv2.imshow('cam', frame)
    cv2.waitKey(10)
```

Output:
![streaming](https://user-images.githubusercontent.com/22151612/65498210-c8c33e00-debb-11e9-9929-cbcb8cbc5a01.gif)

Regarding Ffmpeg command, could you please provide the error log when you run the command above on your machine?

Regarding your last point: The Huddly application does not show the camera feed! It is only used to perform camera controls (autozoom switch, pan, tilt, zoom) and camera upgrades.

**Comment by FreedCapybara** [comment]
I tried that script from IDLE and plain ol' cmd and it worked 👍 

From my previous example, it looks like that `time.sleep(10)` must have been stopping the thread before it could display an image. Here's the corrected code:
```python
from imutils.video import VideoStream
import cv2

# Using src=0 since Huddly IQ is the only camera connected to the host machine
vs = VideoStream(src=0, resolution=(1920, 1080)).start()

frame = vs.read()
cv2.imshow('cam', frame)
cv2.waitKey(0)
```

Since that Python script is working for me now, I don't care about Ffmpeg anymore 👍 

Thank you! I don't really know why I had so much trouble arriving at that, but I guess that's how it goes sometimes ¯\_(ツ)_/¯
