### ISSUE TITLE
Keep getting note when running Huddly SDK index.js for the Azure connector

### ISSUE THREAD

**Issue by MCL-Fulljames** [Huddly/sdk#234]
I am trying to connect my Huddly to Azure, it seems to connect OK as seen in the below screenshot but does not seem to send any data. 
![image](https://user-images.githubusercontent.com/51404084/68336492-6e321a00-00d6-11ea-84bd-aebd694ae3c6.png)

When I run index.js I get the below note. 

`** NB ** Host application must stream main in order to get detection events IQ Detector`

The code I am working on can be found [here](https://github.com/Huddly/sdk/tree/master/examples/azure_iot).

**Comment by jontore** [comment]
Hi @MCL-Fulljames that is because in this example you need to stream video from the camera in order to get detections. So you need to use the camera in a VCA. (for instance zoom, skype)

The other option is to get detections always, you can do this by changing the detector options ```DOWS: false```
https://github.com/Huddly/sdk/blob/3b462f73cdd51032b69619c99fc42625c677c8b0/examples/azure_iot/src/huddlyService.js#L49
