### ISSUE TITLE
Cannot use camera (reliably) when count is enabled

### ISSUE THREAD

**Issue by hroblesm** [Huddly/sdk#250]
Sometimes if we start the camera, and then start people count it works.
Most of the time, if we start people count, then start the camera - it does not work

Is there a "reliable" way we can get the Huddly people count AND have the video stream to another application such as MS camera or VLC media player.

**Comment by jontore** [comment]
Hi @hroblesm.

 That should work, as documented there is a way to get detections without streaming in a VCA (https://developer.huddly.com/#how-do-i-get-detections-only-when-i-am-streaming-with-my-huddly-iq). 

Can you please describe the steps and what code you're running, and please provide camerasw and sdk version as well.

And we can look into it.

**Comment by hroblesm** [comment]
Hi @jontore 

What we want is this.

1. Start the headcount even if any application is streaming by using the Headdly IQ camera. (May be I could be wrong, but if no application is streaming with the Huddly IQ camera, not headcount is detected. The only way we are being able to get the headcount is by using the AForge.Video.DirectShow library to detect the camera and start it.

2. Since we are starting the camera with the AForge.Video.DirectShow library, when use other application to stream with the Huddly IQ camera, a error popup is shown and address the device is being used by another application.

camerasw is: HuddlyIQ-1.3.13-68881
 sdk is:
    "@huddly/device-api-usb": "^0.2.6",
    "@huddly/sdk": "^0.3.1"

Code:
[app-js.txt](https://github.com/Huddly/sdk/files/3898107/app-js.txt)

**Comment by jontore** [comment]
Hi, with the latest version of the SDK (newer then 0.4) and camera sw it is no longer necessary to stream with a VCA to get detections. 

https://github.com/Huddly/sdk/blob/master/examples/target_camera/index.js

The problem you're running into is that on windows only one application can take the stream at the time. So the video stream needs to be released so that a different application can take it.

Hope that answers your question.

**Comment by jontore** [comment]
Close due to inactivity
