### ISSUE TITLE
Turn LED light off

### ISSUE THREAD

**Issue by MCL-Fulljames** [Huddly/sdk#283]
I can successfully use this SDK to detect people, but how can I do so without activating the LED light on the camera?

**Comment by brikendr** [comment]
Hi @MCL-Fulljames 

Thank you for using the SDK and submitting questions/issues.

Getting detection data from the camera without turning the LED light on is not possible by design. Since the camera always relies on having an active stream (main stream or internal stream when you set DOWS detection option to `false`) to get detections out, the LED light is an indication to the user that the stream is being used.
