### ISSUE TITLE
Issue using REST API

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#38]
I downloaded huddly/sdk from git. And followed the instructions in [this link](https://developer.huddly.com/additional-documentation/rest-api.html) . The command "npm run start" did not start the REST server, instead came back with the following erro:
`npm ERR! missing script: start 
`

**Comment by brikendr** [comment]
Hi @qmas thank you for submitting this issue.

In order to properly run the examples on the `examples` folder you need to treat them as separate individual projects. In your case I am assuming that you are running `npm run start` from the root directory, instead of the `examples/rest` directory. The REST API example which is located under `examples/rest` has its own `package.json` file and you should run the commands sepcified at [rest api example](https://developer.huddly.com/additional-documentation/rest-api.html) under that directory instead.

Please try this and let us know how it goes.

**Comment by qmas** [comment]
Thanks it worked. Can you point me a Nodejs sample that displays video on the laptop.

**Comment by brikendr** [comment]
Hey @qmas,

You can take a look at the [WebRTC samples](https://webrtc.github.io/samples/) where you can do different things like rendering the camera stream in different resolutions, recording the stream, and even an example of how to implement your own video chat. The examples are in javascript which can be used in a nodejs application rendered on the browser.

Closing this issue since your initial question as been resolved!
