### ISSUE TITLE
Is HuddlyIQ camera attached ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#58]
1. Using Huddly SDK, Is there a way to know if a Huddly camera is attached?
2. If camera is not attached and I make sdk call, the code never comes out. Is there a way for the call to timeout

**Comment by jontore** [comment]
The camera manager emits an ```ATTACH``` event when the camera is attached, you can listen to this. 

```
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', (cameraManager) => {});
}

init()

```

**Comment by qmas** [comment]
And if the camera is not attached. In that case what will be returned and where in code?

**Comment by brikendr** [comment]
@qmas the Huddly SDK is an event driven class when it comes to device discovery!
If you have initialized the SDK on your app and you are listening to ATTACH and DETACH events, those events will be invoked if and only if a camera is plugged/unplugged from your host machine. 

In other words, nothing happens if you initialize the Huddly SDK and there is no camera attached to the host machine. The event will still be there listening but is invoked only when you plug in the camera.

I hope this answers your question!

**Comment by qmas** [comment]
Consider an app using Huddly sdk. If camera is NOT attached and someone runs this app, then this app will never terminate. Is there a way to timeout listening ATTACH event so that the app could be terminated.

**Comment by jontore** [comment]
@qmas You can write a timeout that takes down the application if no attach event has been emitted within a certain time.

Here is an example that stops the process with -1 if the camera is not attached within 5s.
```

const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const usbApi = new HuddlyDeviceAPIUSB();
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => reject('NO CAMERA ATTACHED'), 5000);
    sdk.on('ATTACH', (cameraManager) => {
      clearTimeout(timeoutId)
      resolve();
    });
  });
}

init().catch((e) => {
  console.warn(e);
  process.exit(-1);
});

```

**Comment by qmas** [comment]
Ok thanks this will work.  You may close this issue
